version: '3.8'
services:
  db:
    image: postgres
    env_file: ./.env
  sinatra-api:
    build: ./sinatra_api
    command: bash -c "rm -f tmp/pids/server.pid && RACK_ENV=development bundle exec puma"
    volumes:
      - .:/sinatra-api
    ports:
      - "55755:55755"
    depends_on:
      - db
    env_file: ./sinatra_api/.env
  react-app:
    build: ./react_app
    # command: bash -c "npm install && npm start"
    command: bash -c "sleep 2"
    volumes:
      - .:/react-app
    ports:
      - "1337:1337"
    depends_on:
      - sinatra-api
    env_file: ./react_app/.env
volumes:
  postgres: